apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-one
  namespace: vigneshbaskar-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-one
  template:
    metadata:
      labels:
        app: deploy-one
    spec:
      volumes:
        - name: applogs
          emptyDir: {}
        - name: promtail-config
          configMap:
            name: promtail-config
      containers:
        - name: app
          image: prom/node-exporter:latest
          ports:
            - containerPort: 9100
          volumeMounts:
            - name: applogs
              mountPath: /var/log/app-logs
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Start Node Exporter in the background
              /bin/node_exporter &
              # Log generator
              while true; do
                echo "$(date) Hello from deploy-one" >> /var/log/app-logs/app.log;
                sleep 5;
              done

        - name: promtail
          image: grafana/promtail:3.1.0
          args:
            - -config.file=/etc/promtail/config/promtail.yaml
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail/config
            - name: applogs
              mountPath: /var/log/app-logs
