apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: parashuram-n-dev
data:
  prometheus.yml: |
    # my global config
    global:
      scrape_interval: 30s
      evaluation_interval: 30s

    # Alertmanager configuration
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - "alertmanager:9093"   # Using ClusterIP for Alertmanager

    # Load rules once and periodically evaluate them according to the global 'evaluation_interval'
    rule_files:
      - "/etc/prometheus/rules/alert.rules.yml"

    # Scrape configurations
    scrape_configs:
      # Monitor Prometheus itself
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
            labels:
              app: "prometheus"

      # Monitor deploy-one application
      - job_name: "deploy-one"
        static_configs:
          - targets: ["deploy-one:9100"]
            labels:
              app: "deploy-one"

      # Monitor deploy-two application
      - job_name: "deploy-two"
        static_configs:
          - targets: ["deploy-two:9100"]
            labels:
              app: "deploy-two"
